from __future__ import annotations

import subprocess
from pathlib import Path

from yield_report.agent.omp_runtime import OmpJsonRuntime, OmpRuntimeConfig
from yield_report.agent.runtime_adapter import RuntimeRouter
from yield_report.agent.spec_model import RunContext, SkillCall, SkillError, SkillResult, TaskSpec


def test_omp_runtime_builds_run_scoped_prompt_and_parses_events(
    monkeypatch,
    tmp_path: Path,
) -> None:
    calls: list[list[str]] = []

    def fake_run(command, **kwargs):
        calls.append(command)
        return subprocess.CompletedProcess(
            args=command,
            returncode=0,
            stdout='{"type":"message","message":"分析完成"}\n',
            stderr="",
        )

    monkeypatch.setattr("shutil.which", lambda command: command)
    monkeypatch.setattr("subprocess.run", fake_run)
    run_dir = tmp_path / "specs" / "runs" / "run-pi"
    context = RunContext(
        run_id="run-pi",
        workspace=tmp_path,
        spec_path=run_dir / "spec.yaml",
        output_dir=run_dir / "outputs",
        config={"run_dir": str(run_dir)},
    )
    runtime = OmpJsonRuntime(config=OmpRuntimeConfig(command="omp", timeout_seconds=5))

    results = runtime.run_spec(
        TaskSpec(
            run_id="run-pi",
            workflow=[SkillCall(id="analyze", skill="data_analysis")],
            outputs={"analysis_summary": {"required": True}},
        ),
        context,
    )

    assert results[0].success is True
    assert "分析完成" in results[0].data["result_text"]
    assert (run_dir / "pi_prompt.md").exists()
    assert (run_dir / "pi_events.jsonl").exists()
    assert "--mode" in calls[0]
    assert "--session-dir" in calls[0]


def test_omp_runtime_uses_generated_markdown_when_events_have_no_text(
    monkeypatch,
    tmp_path: Path,
) -> None:
    run_dir = tmp_path / "specs" / "runs" / "run-pi-markdown"
    output_dir = run_dir / "outputs"

    def fake_run(command, **kwargs):
        output_dir.mkdir(parents=True, exist_ok=True)
        (output_dir / "analysis_summary.md").write_text(
            "# M588 analysis\n\nGenerated by OMP.",
            encoding="utf-8",
        )
        return subprocess.CompletedProcess(
            args=command,
            returncode=0,
            stdout='{"type":"status","status":"done"}\n',
            stderr="",
        )

    monkeypatch.setattr("shutil.which", lambda command: command)
    monkeypatch.setattr("subprocess.run", fake_run)
    context = RunContext(
        run_id="run-pi-markdown",
        workspace=tmp_path,
        spec_path=run_dir / "spec.yaml",
        output_dir=output_dir,
        config={"run_dir": str(run_dir)},
    )

    results = OmpJsonRuntime(config=OmpRuntimeConfig(command="omp")).run_spec(
        TaskSpec(run_id="run-pi-markdown"),
        context,
    )

    assert results[0].success is True
    assert "M588 analysis" in results[0].data["result_text"]
    assert any(artifact.path.name == "analysis_summary.md" for artifact in results[0].artifacts)


def test_omp_runtime_reports_blocker_from_trace(
    monkeypatch,
    tmp_path: Path,
) -> None:
    run_dir = tmp_path / "specs" / "runs" / "run-pi-blocked"
    output_dir = run_dir / "outputs"

    def fake_run(command, **kwargs):
        output_dir.mkdir(parents=True, exist_ok=True)
        (output_dir / "analysis_summary.md").write_text(
            "# Partial analysis\n\nFineReport redownload was blocked.",
            encoding="utf-8",
        )
        (run_dir / "trace.jsonl").write_text(
            '{"step":"blocker","status":"blocked","detail":"FineReport RPA timeout"}\n',
            encoding="utf-8",
        )
        return subprocess.CompletedProcess(
            args=command,
            returncode=0,
            stdout='{"type":"status","status":"done"}\n',
            stderr="",
        )

    monkeypatch.setattr("shutil.which", lambda command: command)
    monkeypatch.setattr("subprocess.run", fake_run)
    context = RunContext(
        run_id="run-pi-blocked",
        workspace=tmp_path,
        spec_path=run_dir / "spec.yaml",
        output_dir=output_dir,
        config={"run_dir": str(run_dir)},
    )

    results = OmpJsonRuntime(config=OmpRuntimeConfig(command="omp")).run_spec(
        TaskSpec(run_id="run-pi-blocked"),
        context,
    )

    assert results[0].success is False
    assert results[0].error is not None
    assert results[0].error.code == "omp.blocked"
    assert "FineReport RPA timeout" in results[0].error.message
    assert "Partial analysis" in results[0].data["result_text"]


def test_omp_runtime_preserves_partial_artifacts_on_timeout(
    monkeypatch,
    tmp_path: Path,
) -> None:
    run_dir = tmp_path / "specs" / "runs" / "run-pi-timeout"
    output_dir = run_dir / "outputs"

    def fake_run(command, **kwargs):
        output_dir.mkdir(parents=True, exist_ok=True)
        (output_dir / "analysis_summary.md").write_text(
            "# Partial timeout analysis\n\nRPA was still waiting.",
            encoding="utf-8",
        )
        raise subprocess.TimeoutExpired(
            cmd=command,
            timeout=5,
            output='{"message":"partial stdout"}\n',
            stderr="still waiting",
        )

    monkeypatch.setattr("shutil.which", lambda command: command)
    monkeypatch.setattr("subprocess.run", fake_run)
    context = RunContext(
        run_id="run-pi-timeout",
        workspace=tmp_path,
        spec_path=run_dir / "spec.yaml",
        output_dir=output_dir,
        config={"run_dir": str(run_dir)},
    )

    results = OmpJsonRuntime(config=OmpRuntimeConfig(command="omp", timeout_seconds=5)).run_spec(
        TaskSpec(run_id="run-pi-timeout"),
        context,
    )

    assert results[0].success is False
    assert results[0].error is not None
    assert results[0].error.code == "omp.timeout"
    assert "Partial timeout analysis" in results[0].data["result_text"]
    assert any(artifact.path.name == "analysis_summary.md" for artifact in results[0].artifacts)


def test_omp_runtime_returns_structured_failure_on_nonzero_exit(
    monkeypatch,
    tmp_path: Path,
) -> None:
    def fake_run(command, **kwargs):
        return subprocess.CompletedProcess(args=command, returncode=7, stdout="", stderr="bad auth")

    monkeypatch.setattr("shutil.which", lambda command: command)
    monkeypatch.setattr("subprocess.run", fake_run)
    run_dir = tmp_path / "specs" / "runs" / "run-pi-fail"
    context = RunContext(
        run_id="run-pi-fail",
        workspace=tmp_path,
        spec_path=run_dir / "spec.yaml",
        output_dir=run_dir / "outputs",
        config={"run_dir": str(run_dir)},
    )

    results = OmpJsonRuntime().run_spec(TaskSpec(run_id="run-pi-fail"), context)

    assert results[0].success is False
    assert results[0].error is not None
    assert results[0].error.code == "omp.nonzero_exit"


def test_runtime_router_explicit_python_uses_deterministic_runtime(tmp_path: Path) -> None:
    class FakePython:
        def run_spec(self, spec: TaskSpec, context: RunContext):
            return [SkillResult(skill_name="data_analysis", success=True, summary="python ok")]

    class FakeOmp:
        def run_spec(self, spec: TaskSpec, context: RunContext):
            raise AssertionError("explicit python runtime must not call OMP")

    spec = TaskSpec(
        run_id="run-router",
        constraints={"runtime": "python_with_pi_fallback"},
        workflow=[SkillCall(id="analyze", skill="data_analysis")],
        outputs={"analysis_summary": {"required": True}},
    )

    result = RuntimeRouter(python_runtime=FakePython(), omp_runtime=FakeOmp()).run_spec(
        spec,
        RunContext(run_id="run-router", workspace=tmp_path),
        requested_runtime="python",
    )

    assert result.runtime == "python"
    assert result.fallback_attempted is False
    assert result.success is True


def test_runtime_router_auto_uses_explicitly_configured_python_default(tmp_path: Path) -> None:
    class FakePython:
        def run_spec(self, spec: TaskSpec, context: RunContext):
            return [SkillResult(skill_name="data_analysis", success=True, summary="python ok")]

    class FakeOmp:
        def run_spec(self, spec: TaskSpec, context: RunContext):
            raise AssertionError("auto runtime must not call OMP when default_runtime=python")

    result = RuntimeRouter(
        python_runtime=FakePython(),
        omp_runtime=FakeOmp(),
        default_runtime="python",
    ).run_spec(
        TaskSpec(run_id="run-python-default"),
        RunContext(run_id="run-python-default", workspace=tmp_path),
        requested_runtime="auto",
    )

    assert result.runtime == "python"
    assert result.fallback_attempted is False
    assert result.success is True


def test_runtime_router_falls_back_to_python_when_auto_omp_startup_fails(tmp_path: Path) -> None:
    class FakePython:
        def run_spec(self, spec: TaskSpec, context: RunContext):
            return [SkillResult(skill_name="data_analysis", success=True, summary="python ok")]

    class FakeOmp:
        def run_spec(self, spec: TaskSpec, context: RunContext):
            return [
                SkillResult(
                    skill_name="pi_agent",
                    success=False,
                    summary="Pi/OMP runtime failed: ReferenceError: window is not defined",
                    error=SkillError(
                        code="omp.nonzero_exit",
                        message="ReferenceError: window is not defined at swagger-ui-bundle.js",
                    ),
                )
            ]

    spec = TaskSpec(
        run_id="run-router-omp-fallback",
        constraints={"runtime": "omp"},
        workflow=[SkillCall(id="analyze", skill="data_analysis")],
    )

    result = RuntimeRouter(
        python_runtime=FakePython(),
        omp_runtime=FakeOmp(),
        default_runtime="python",
    ).run_spec(
        spec,
        RunContext(run_id="run-router-omp-fallback", workspace=tmp_path),
        requested_runtime="auto",
    )

    assert result.runtime == "python"
    assert result.fallback_attempted is True
    assert result.success is True
    assert "Pi/OMP runtime failed" in result.results[0].warnings[0]


def test_omp_runtime_prompt_contains_task16_workflow_guardrails(tmp_path: Path) -> None:
    run_dir = tmp_path / "specs" / "runs" / "run-task16"
    context = RunContext(
        run_id="run-task16",
        workspace=tmp_path,
        spec_path=run_dir / "spec.yaml",
        output_dir=run_dir / "outputs",
        config={"run_dir": str(run_dir)},
    )
    spec = TaskSpec(
        run_id="run-task16",
        user_goal="请分析M588近三个月的良率变化趋势；如果有恶化，请给出恶化原因",
        inputs={
            "report_date": "2026-06-15",
            "analysis": {"time_grain": "monthly", "requested_periods": 3},
        },
        workflow=[SkillCall(id="analyze", skill="data_analysis")],
    )

    prompt = OmpJsonRuntime._build_prompt(spec, context)

    assert "OMP 是本次运行的唯一 Agent Runtime" in prompt
    assert "结束日期" in prompt
    assert "超过 1 天" in prompt
    assert "month_count" in prompt
    assert "Table Schema Detect" in prompt
    assert "docs/references/table_schema" in prompt
    assert "不要无限等待" in prompt
    assert "用户修正" in prompt


def test_omp_runtime_command_auto_approves_project_tools(tmp_path: Path) -> None:
    context = RunContext(run_id="run-cmd", workspace=tmp_path)
    runtime = OmpJsonRuntime(config=OmpRuntimeConfig(command="omp"))

    command = runtime._build_command(context, tmp_path / "prompt.md", "omp")

    assert "--auto-approve" in command


def test_omp_runtime_finds_windows_localappdata_install(
    monkeypatch,
    tmp_path: Path,
) -> None:
    local_app_data = tmp_path / "LocalAppData"
    command = local_app_data / "omp" / "omp.exe"
    command.parent.mkdir(parents=True)
    command.write_text("fake", encoding="utf-8")

    monkeypatch.setenv("LOCALAPPDATA", str(local_app_data))
    monkeypatch.delenv("YIELD_REPORT_OMP_COMMAND", raising=False)
    monkeypatch.delenv("OMP_COMMAND", raising=False)
    monkeypatch.setattr("shutil.which", lambda command: None)

    runtime = OmpJsonRuntime(config=OmpRuntimeConfig(command="omp"))

    assert runtime.is_available() is True
    assert runtime._resolve_command() == str(command)


def test_omp_runtime_respects_env_command(monkeypatch, tmp_path: Path) -> None:
    command = tmp_path / "custom-omp.exe"
    command.write_text("fake", encoding="utf-8")

    monkeypatch.setenv("YIELD_REPORT_OMP_COMMAND", str(command))
    monkeypatch.setattr("shutil.which", lambda command: None)

    runtime = OmpJsonRuntime(config=OmpRuntimeConfig(command="omp"))

    assert runtime._resolve_command() == str(command)
